# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='fieldform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formulaire.Form'),
        ),
    ]
