# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(default='Default title', max_length=200),
        ),
    ]
